name: Marsvin matrix library check jobs
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-run-unit-test:
    name: Build and Run unit-test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install gtest
        run: |
          git clone -q https://github.com/google/googletest.git
          cd googletest
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install
      - name: Build Project
        run: |
          rm -rf build
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Run unit-test
        run: |
          cd build
          ctest --verbose
  clang-format-check:
    name: Run clang-format-15
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format-15
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main"
          sudo apt-get update
          sudo apt-get install -y clang-15 clang-format-15
      - name: Run clang-format-15 in source code
        run: |
          clang-format-15 --Werror --dry-run core/include/* core/src/*

  doxygen-build:
    name: Build Doxygen documentation
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Build documentation
        run: |
          cd documentation
          doxygen

