name: Marsvin matrix library deploy jobs
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  deploy-doxygen:
    name: Build and Deploy Doxygen documentation
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
      - name: Build documentation
        run: |
          cd documentation
          doxygen
      - name: Publish HTML files
        uses: actions/upload-pages-artifact@v2
        with:
          path: documentation/output-dir/html


